server:
  port: 8080
logging:
  level:
    com.littlejenny.gulimall: debug
spring:
  application:
    name: seckill
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
      cache: false
    mvc:
      date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: gulimall-redis.guli
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: gulimall-nacos.guli:8848
        #namespace: 1047922a-261d-4df4-9875-abc4e3a3cc53
        group: prod
    sentinel:
      transport:
        dashboard: gulimall-sentinel.guli:8858
        port: 8719
  task:
    execution:
      pool:
        core-size: 8
        max-size: 50
        queue-capacity: 200000
  rabbitmq:
    host: gulimall-rabbitmq.guli
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true

