Spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 791ccfe7-90ed-4d0a-8d46-eb3febf4b131
        extension-configs[0]:
          data-id: BaseConfig.yaml
          group: dev   # 默认为DEFAULT_GROUP
          refresh: true   # 是否动态刷新，默认为false
        extension-configs[1]:
          data-id: NacosService.yaml
          group: dev
          refresh: true
        extension-configs[2]:
          data-id: Mybatis.yaml
          group: dev
          refresh: true
        extension-configs[3]:
          data-id: DataSource.yaml
          group: dev
          refresh: true
        extension-configs[4]:
          data-id: Rabbitmq.yaml
          group: dev
          refresh: true
        extension-configs[5]:
          data-id: Redis.yaml
          group: dev
          refresh: true
        extension-configs[6]:
          data-id: ThreadPool.yaml
          group: dev
          refresh: true
        extension-configs[7]:
          data-id: Sentinel.yaml
          group: dev
          refresh: true
spring:
  session:
    store-type: redis







