Spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 02457fd1-13f8-4e6e-af08-0a90c90dc676
        extension-configs[0]:
          data-id: BaseConfig.yaml
          group: dev   # 默认为DEFAULT_GROUP
          refresh: true   # 是否动态刷新，默认为false
        extension-configs[1]:
          data-id: NacosService.yaml
          group: dev
          refresh: true
        extension-configs[2]:
          data-id: DataSource.yaml
          group: dev
          refresh: true
        extension-configs[3]:
          data-id: Rabbitmq.yaml
          group: dev
          refresh: true
        extension-configs[4]:
          data-id: Sentinel.yaml
          group: dev
          refresh: true









