server:
  port: 8080
logging:
  level:
    com.littlejenny.gulimall: debug
spring:
  application:
    name: rabbitmq
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
      cache: false
  cloud:
    nacos:
      discovery:
        server-addr: gulimall-nacos.guli:8848
        #namespace: 1047922a-261d-4df4-9875-abc4e3a3cc53
        group: prod
    sentinel:
      transport:
        dashboard: gulimall-sentinel.guli:8858
        port: 8719
  rabbitmq:
    host: gulimall-rabbitmq.guli
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gulimall-mysql-master.guli:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true